#!/usr/bin/env python3
"""Aggregate v1_bench_matrix cert JSONs into REPORT.md.

Reads every `<tag>.json` in this directory, emits a top-level
markdown report with:
- one model x quant header
- per-topology row (mesh1/pp2/tp2/pp4/pp2tp2 + batched siblings)
- columns for each prefill / decode length seen across all certs
- "winner" annotations for prefill / decode per model
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
TOPOLOGY_ORDER = {"mesh1": 0, "pp2": 1, "tp2": 2, "pp4": 3, "pp2tp2": 4}


def load_certs():
    certs = []
    for p in sorted(HERE.glob("*.json")):
        if p.name.startswith("_"):
            continue
        try:
            d = json.loads(p.read_text())
            certs.append((p.stem, d))
        except Exception as e:
            print(f"skip {p.name}: {e}", file=sys.stderr)
    return certs


def cert_table(cert):
    """Return (header_row, rows) for one cert."""
    prefill = cert.get("prefill_lengths", [])
    decode = cert.get("decode_lengths", [])
    header = (
        ["topology", "pp", "tp", "load_s"]
        + [f"pp{l}" for l in prefill]
        + [f"tg{l}" for l in decode]
    )
    rows = []
    topologies = sorted(
        cert["topologies"], key=lambda t: TOPOLOGY_ORDER.get(t["tag"], 99)
    )
    for top in topologies:
        runs = top["runs"]
        # baseline row
        prefill_vals = [
            next((r["tok_per_sec"] for r in runs if r["phase"] == "prefill" and r["n_tokens"] == l), None)
            for l in prefill
        ]
        decode_vals = [
            next((r["tok_per_sec"] for r in runs if r["phase"] == "decode" and r["n_tokens"] == l), None)
            for l in decode
        ]
        rows.append([top["tag"], top["pp_size"], top["tp_size"], f"{top['load_secs']:.2f}"]
                    + prefill_vals + decode_vals)
        # batched row if present
        has_batched = any(r["phase"] == "prefill_batched" for r in runs)
        if has_batched:
            batched_vals = [
                next((r["tok_per_sec"] for r in runs if r["phase"] == "prefill_batched" and r["n_tokens"] == l), None)
                for l in prefill
            ]
            rows.append([f"{top['tag']}+batched", top["pp_size"], top["tp_size"], "—"]
                        + batched_vals + [None] * len(decode))
    return header, rows


def fmt_cell(v):
    if v is None:
        return "—"
    if isinstance(v, (int, str)):
        return str(v)
    return f"{v:.1f}"


def md_table(header, rows):
    out = ["| " + " | ".join(str(h) for h in header) + " |"]
    out.append("|" + "|".join("---" for _ in header) + "|")
    for r in rows:
        out.append("| " + " | ".join(fmt_cell(c) for c in r) + " |")
    return "\n".join(out)


def winner(cert, phase, n_tokens):
    """Return (topology_tag, tok_per_sec) of the winner for this metric."""
    best = (None, 0.0)
    for top in cert["topologies"]:
        for r in top["runs"]:
            if r["phase"] == phase and r["n_tokens"] == n_tokens:
                tag = top["tag"]
                if r["tok_per_sec"] > best[1]:
                    best = (tag, r["tok_per_sec"])
        # also check batched
        for r in top["runs"]:
            if r["phase"] == "prefill_batched" and r["n_tokens"] == n_tokens and phase == "prefill":
                tag = f"{top['tag']}+batched"
                if r["tok_per_sec"] > best[1]:
                    best = (tag, r["tok_per_sec"])
    return best


def main():
    certs = load_certs()
    if not certs:
        print("no certs found", file=sys.stderr)
        sys.exit(1)

    # Load llama.cpp comparison if available.
    llamacpp_dir = HERE / "llamacpp"
    llamacpp = {}
    if llamacpp_dir.exists():
        for p in llamacpp_dir.glob("*.json"):
            try:
                d = json.loads(p.read_text())
                pp = next(
                    (r["avg_ts"] for r in d if r.get("n_prompt", 0) > 0 and r.get("n_gen", 0) == 0),
                    None,
                )
                tg = next(
                    (r["avg_ts"] for r in d if r.get("n_prompt", 0) == 0 and r.get("n_gen", 0) > 0),
                    None,
                )
                llamacpp[p.stem] = {"pp512": pp, "tg64": tg}
            except Exception as e:
                print(f"skip llamacpp/{p.name}: {e}", file=sys.stderr)

    out = [
        "# V1 Bench Matrix — flambeau vs llama.cpp on 4× MI50 (100 W, ROCm 7.1.1)",
        "",
        "Generated by `aggregate_report.py`. flambeau certs from `<tag>.json`;",
        "llama.cpp certs from `llamacpp/<tag>.json` (llama-bench `-p 512 -n 64",
        "-ngl 99 -sm layer -fa 1 -r 2`, with `ROCBLAS_TENSILE_LIBPATH=/opt/rocm-7.1.1/core-7.13/lib/rocblas/library`).",
        "",
        "tp4 omitted across all models (rig {2,3} BAR1 fault).",
        "Hybrid pp2tp2 uses devices [0,2,1,3] to keep {2,3} out of any TP group.",
        "",
        "## Per-model headline — flambeau vs llama.cpp",
        "",
        "| model+quant | flambeau best topo | flambeau pp512 | flambeau tg64 | llama.cpp pp512 | llama.cpp tg64 | flambeau / llama.cpp pp | tg |",
        "|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    for tag, cert in certs:
        p_top, p_v = winner(cert, "prefill", 512)
        d_top, d_v = winner(cert, "decode", 64)
        lc = llamacpp.get(tag, {})
        lc_pp = lc.get("pp512")
        lc_tg = lc.get("tg64")
        ratio_pp = (
            f"{p_v / lc_pp:.2f}×" if (lc_pp and p_v) else "—"
        )
        ratio_tg = f"{d_v / lc_tg:.2f}×" if (lc_tg and d_v) else "—"
        lc_pp_s = f"{lc_pp:.1f}" if lc_pp else "—"
        lc_tg_s = f"{lc_tg:.1f}" if lc_tg else "—"
        out.append(
            f"| {tag} | {p_top} | **{p_v:.1f}** | **{d_v:.1f}** ({d_top}) | {lc_pp_s} | {lc_tg_s} | {ratio_pp} | {ratio_tg} |"
        )
    out.append("")

    out.append("## Per-model full sweep")
    out.append("")
    for tag, cert in certs:
        out.append(f"### {tag}")
        out.append("")
        out.append(f"GGUF: `{cert.get('gguf_path', '')}`")
        out.append("")
        header, rows = cert_table(cert)
        out.append(md_table(header, rows))
        out.append("")

    report = "\n".join(out) + "\n"
    out_path = HERE / "REPORT.md"
    out_path.write_text(report)
    print(f"wrote {out_path}")
    print(f"  {len(certs)} models")


if __name__ == "__main__":
    main()
