//! Compile every `src/kernels/*.cu` through `hipcc` → `.hsaco`, then emit
//! `hsaco.rs` so `lib.rs` can `include_bytes!` the compiled code objects.
//!
//! Ports candle's `candle-hip-kernels/build.rs`. Only changes:
//! - sources live under `src/kernels/` so `src/lib.rs` and `src/*.rs` stay
//!   Rust-sided;
//! - include path is `src/arch_primitives/` + `../kernels-shared/include/`
//!   (architecture rule 5: shared `.cuh` is backend-neutral);
//! - default `--offload-arch=gfx906` only (V1 arch), overridable via
//!   `HIP_OFFLOAD_ARCH=gfx906,gfx908,...` when a second arch is needed.
//!
//! `HIP_SKIP_BUILD=1` short-circuits the hipcc invocation — useful for CI
//! lint hosts without ROCm, and for `cargo check` in sandboxes.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/kernels");
    println!("cargo:rerun-if-changed=src/arch_primitives");
    println!("cargo:rerun-if-changed=../kernels-shared/include");
    println!("cargo:rerun-if-env-changed=ROCM_PATH");
    println!("cargo:rerun-if-env-changed=HIP_OFFLOAD_ARCH");
    println!("cargo:rerun-if-env-changed=HIP_SKIP_BUILD");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let src_dir = Path::new("src/kernels");
    let arch_inc = Path::new("src/arch_primitives");
    let shared_inc = Path::new("../kernels-shared/include");

    let skip_build = env::var_os("HIP_SKIP_BUILD").is_some();
    let cu_files = enumerate_cu_files(src_dir);

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if !skip_build && !cu_files.is_empty() {
        let rocm_path = env::var("ROCM_PATH").unwrap_or_else(|_| "/opt/rocm".into());
        let hipcc = find_hipcc(&rocm_path)
            .expect("hipcc not found — set ROCM_PATH or HIP_SKIP_BUILD=1 to build without kernels");
        let arch = env::var("HIP_OFFLOAD_ARCH").unwrap_or_else(|_| "gfx906".into());

        for cu in &cu_files {
            let stem = cu.file_stem().unwrap().to_string_lossy().into_owned();
            let hsaco = out_dir.join(format!("{stem}.hsaco"));
            compile_cu(&hipcc, cu, &hsaco, &arch, arch_inc, shared_inc, src_dir);
            entries.push((stem, hsaco));
        }
    }

    let mut hsaco_rs = String::from("// Auto-generated by kernels-hip/build.rs. Do not edit.\n\n");
    for (stem, path) in &entries {
        let const_name = stem.to_uppercase();
        writeln!(
            hsaco_rs,
            "pub const {const_name}_HSACO: &[u8] = include_bytes!(r\"{}\");",
            path.display()
        )
        .expect("write to String is infallible");
    }
    hsaco_rs.push_str("\npub static CATALOGUE: &[(&str, &[u8])] = &[\n");
    for (stem, _) in &entries {
        let const_name = stem.to_uppercase();
        writeln!(hsaco_rs, "    (\"{stem}\", {const_name}_HSACO),")
            .expect("write to String is infallible");
    }
    hsaco_rs.push_str("];\n");
    fs::write(out_dir.join("hsaco.rs"), hsaco_rs).expect("write hsaco.rs");
}

fn enumerate_cu_files(dir: &Path) -> Vec<PathBuf> {
    if !dir.exists() {
        return vec![];
    }
    fs::read_dir(dir)
        .expect("read kernels dir")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "cu"))
        .collect()
}

fn find_hipcc(rocm_path: &str) -> Option<PathBuf> {
    // Prefer the hipcc that lives inside the requested ROCM_PATH — mixing
    // toolchains from different ROCm installs produces subtly-broken
    // `.hsaco` (candle's memory: "7.2.1 RCCL is slower on gfx906; use 7.1.1").
    let candidates = [
        PathBuf::from(rocm_path).join("bin/hipcc"),
        PathBuf::from("/opt/rocm-7.1.1/bin/hipcc"),
        PathBuf::from("/opt/rocm/bin/hipcc"),
        PathBuf::from("/usr/bin/hipcc"),
        PathBuf::from("/usr/local/bin/hipcc"),
    ];
    candidates.into_iter().find(|p| p.exists()).or_else(|| {
        env::var_os("PATH").and_then(|paths| {
            env::split_paths(&paths)
                .map(|p| p.join("hipcc"))
                .find(|p| p.exists())
        })
    })
}

fn compile_cu(
    hipcc: &Path,
    cu: &Path,
    hsaco: &Path,
    arch: &str,
    arch_inc: &Path,
    shared_inc: &Path,
    kernel_inc: &Path,
) {
    // ROCm 7.1.1 installs the device-lib bitcode under
    // `$ROCM_PATH/lib/llvm/lib/clang/20/lib/amdgcn/bitcode`, not
    // `$ROCM_PATH/lib` where 7.2.1's hipcc looks by default. Pass
    // `--rocm-path` explicitly so clang resolves oclc_*.bc via its
    // own `$ROCM_PATH/lib/llvm/...` search tree.
    // 7.1.1's hipcc passes `--hip-device-lib-path=$ROCM_PATH/lib` which is
    // the OLD (pre-7.1) location. The device-lib bitcode in 7.1.1 lives at
    // `$ROCM_PATH/lib/llvm/lib/clang/20/lib/amdgcn/bitcode`. Override with
    // `--hip-device-lib-path` pointing to the right place so clang finds
    // oclc_*.bc.
    let rocm_path = env::var("ROCM_PATH").unwrap_or_else(|_| "/opt/rocm".into());
    let device_lib_paths = [
        format!("{rocm_path}/lib/llvm/lib/clang/20/lib/amdgcn/bitcode"),
        format!("{rocm_path}/amdgcn/bitcode"),
        format!("{rocm_path}/lib"),
    ];
    let device_lib = device_lib_paths
        .iter()
        .find(|p| {
            Path::new(p).join("ocml.bc").exists()
                || Path::new(p).join("oclc_isa_version_906.bc").exists()
        })
        .cloned()
        .unwrap_or_else(|| format!("{rocm_path}/lib"));
    let output = Command::new(hipcc)
        .args([
            "--cuda-device-only",
            "-c",
            "--no-gpu-bundle-output",
            &format!("--offload-arch={arch}"),
            &format!("--rocm-path={rocm_path}"),
            &format!("--hip-device-lib-path={device_lib}"),
            "-std=c++17",
            "-O3",
            "-D__HIP_PLATFORM_AMD__",
            "-DWARP_SIZE=64",
            "-I",
            kernel_inc.to_str().unwrap(),
            "-I",
            arch_inc.to_str().unwrap(),
            "-I",
            shared_inc.to_str().unwrap(),
            "-o",
            hsaco.to_str().unwrap(),
            cu.to_str().unwrap(),
        ])
        .output()
        .unwrap_or_else(|e| panic!("failed to run hipcc at {}: {e}", hipcc.display()));

    let stderr = String::from_utf8_lossy(&output.stderr);
    let stdout = String::from_utf8_lossy(&output.stdout);
    if !stdout.is_empty() {
        println!(
            "cargo:warning=hipcc stdout for {}: {}",
            cu.display(),
            stdout.replace('\n', " | ")
        );
    }
    if !stderr.is_empty() && !output.status.success() {
        println!(
            "cargo:warning=hipcc stderr for {}: {}",
            cu.display(),
            stderr.replace('\n', " | ")
        );
    }
    assert!(
        output.status.success(),
        "hipcc failed for {}:\n--- stderr ---\n{stderr}\n--- stdout ---\n{stdout}",
        cu.display()
    );
}
