use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};
use std::process::Command;

use rayon::prelude::*;
use sha2::{Digest, Sha256};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/kernels");
    println!("cargo:rerun-if-changed=src/arch_primitives");
    println!("cargo:rerun-if-changed=../kernels-shared/include");
    println!("cargo:rerun-if-env-changed=ROCM_PATH");
    println!("cargo:rerun-if-env-changed=HIP_OFFLOAD_ARCH");
    println!("cargo:rerun-if-env-changed=HIP_SKIP_BUILD");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let src_dir = Path::new("src/kernels");
    let arch_inc = Path::new("src/arch_primitives");
    let shared_inc = Path::new("../kernels-shared/include");

    let skip_build = env::var_os("HIP_SKIP_BUILD").is_some();
    let cu_files = enumerate_cu_files(src_dir);

    let mut entries: BTreeMap<String, PathBuf> = BTreeMap::new();
    if !skip_build && !cu_files.is_empty() {
        let rocm_path = env::var("ROCM_PATH").unwrap_or_else(|_| "/opt/rocm".into());
        let hipcc = find_hipcc(&rocm_path)
            .expect("hipcc not found — set ROCM_PATH or HIP_SKIP_BUILD=1 to build without kernels");
        let arch = env::var("HIP_OFFLOAD_ARCH").unwrap_or_else(|_| "gfx906".into());

        let cache_dir = out_dir.join("cache");
        let _ = fs::create_dir_all(&cache_dir);

        let device_lib = find_device_lib_path(&rocm_path);

        // Compile in parallel. hipcc is single-threaded per file; 160 .cu files
        // compiled serially is the dominant build cost. rayon parallelises across
        // all available cores, cutting wall-clock time ~N×.
        let results: Vec<(String, PathBuf)> = cu_files
            .par_iter()
            .map(|cu| {
                let stem = cu.file_stem().unwrap().to_string_lossy().into_owned();
                let hsaco = out_dir.join(format!("{stem}.hsaco"));
                let cache_hash_file = cache_dir.join(format!("{stem}.sha256"));

                let needs_rebuild = needs_rebuild(cu, &hsaco, &cache_hash_file, &arch);

                if needs_rebuild {
                    compile_cu(
                        &hipcc,
                        cu,
                        &hsaco,
                        &arch,
                        IncludeRoots { arch: arch_inc, shared: shared_inc, kernel: src_dir },
                        &device_lib,
                    );
                    let hash = hash_cu_source(cu, &arch);
                    fs::write(&cache_hash_file, &hash).ok();
                }

                (stem, hsaco)
            })
            .collect();
        for (stem, hsaco) in results {
            entries.insert(stem, hsaco);
        }
    }

    let mut hsaco_rs =
        String::from("// Auto-generated by kernels-hip/build.rs. Do not edit.\n\n");
    for (stem, path) in &entries {
        let const_name = stem.to_uppercase();
        writeln!(
            hsaco_rs,
            "pub const {const_name}_HSACO: &[u8] = include_bytes!(r\"{}\");",
            path.display()
        )
        .expect("write to String is infallible");
    }
    hsaco_rs.push_str("\npub static CATALOGUE: &[(&str, &[u8])] = &[\n");
    for stem in entries.keys() {
        let const_name = stem.to_uppercase();
        writeln!(hsaco_rs, "    (\"{stem}\", {const_name}_HSACO),")
            .expect("write to String is infallible");
    }
    hsaco_rs.push_str("];\n");
    fs::write(out_dir.join("hsaco.rs"), hsaco_rs).expect("write hsaco.rs");
}

fn enumerate_cu_files(dir: &Path) -> Vec<PathBuf> {
    if !dir.exists() {
        return vec![];
    }
    fs::read_dir(dir)
        .expect("read kernels dir")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "cu"))
        .collect()
}

fn find_hipcc(rocm_path: &str) -> Option<PathBuf> {
    let candidates = [
        PathBuf::from(rocm_path).join("bin/hipcc"),
        PathBuf::from("/opt/rocm-7.1.1/bin/hipcc"),
        PathBuf::from("/opt/rocm/bin/hipcc"),
        PathBuf::from("/usr/bin/hipcc"),
        PathBuf::from("/usr/local/bin/hipcc"),
    ];
    candidates
        .into_iter()
        .find(|p| p.exists())
        .or_else(|| {
            env::var_os("PATH").and_then(|paths| {
                env::split_paths(&paths)
                    .map(|p| p.join("hipcc"))
                    .find(|p| p.exists())
            })
        })
}

fn find_device_lib_path(rocm_path: &str) -> String {
    let candidates = [
        format!("{rocm_path}/lib/llvm/lib/clang/20/lib/amdgcn/bitcode"),
        format!("{rocm_path}/amdgcn/bitcode"),
        format!("{rocm_path}/lib"),
    ];
    candidates
        .iter()
        .find(|p| {
            Path::new(p).join("ocml.bc").exists()
                || Path::new(p).join("oclc_isa_version_906.bc").exists()
        })
        .cloned()
        .unwrap_or_else(|| format!("{rocm_path}/lib"))
}

fn hash_cu_source(cu: &Path, arch: &str) -> String {
    let mut hasher = Sha256::new();
    let mut f = fs::File::open(cu).expect("open cu file");
    let mut buf = Vec::new();
    f.read_to_end(&mut buf).expect("read cu file");
    hasher.update(&buf);
    hasher.update(arch.as_bytes());
    format!("{:x}", hasher.finalize())
}

fn needs_rebuild(cu: &Path, hsaco: &Path, cache_hash: &Path, arch: &str) -> bool {
    if !hsaco.exists() {
        return true;
    }
    let current_hash = hash_cu_source(cu, arch);
    if !cache_hash.exists() {
        return true;
    }
    let cached_hash =
        fs::read_to_string(cache_hash).unwrap_or_default().trim().to_string();
    current_hash != cached_hash
}

/// Include-path roots passed to `hipcc -I`.
struct IncludeRoots<'a> {
    arch: &'a Path,
    shared: &'a Path,
    kernel: &'a Path,
}

fn compile_cu(
    hipcc: &Path,
    cu: &Path,
    hsaco: &Path,
    arch: &str,
    includes: IncludeRoots<'_>,
    device_lib: &str,
) {
    let IncludeRoots { arch: arch_inc, shared: shared_inc, kernel: kernel_inc } = includes;
    let rocm_path = env::var("ROCM_PATH").unwrap_or_else(|_| "/opt/rocm".into());
    let output = Command::new(hipcc)
        .args([
            "--cuda-device-only",
            "-c",
            "--no-gpu-bundle-output",
            &format!("--offload-arch={arch}"),
            &format!("--rocm-path={rocm_path}"),
            &format!("--hip-device-lib-path={device_lib}"),
            "-std=c++17",
            "-O3",
            "-D__HIP_PLATFORM_AMD__",
            "-DWARP_SIZE=64",
            "-I",
            kernel_inc.to_str().unwrap(),
            "-I",
            arch_inc.to_str().unwrap(),
            "-I",
            shared_inc.to_str().unwrap(),
            "-o",
            hsaco.to_str().unwrap(),
            cu.to_str().unwrap(),
        ])
        .output()
        .unwrap_or_else(|e| panic!("failed to run hipcc at {}: {e}", hipcc.display()));

    let stderr = String::from_utf8_lossy(&output.stderr);
    let stdout = String::from_utf8_lossy(&output.stdout);
    if !stdout.is_empty() {
        eprintln!(
            "hipcc stdout for {}: {}",
            cu.display(),
            stdout.replace('\n', " | ")
        );
    }
    if !stderr.is_empty() && !output.status.success() {
        eprintln!(
            "hipcc stderr for {}: {}",
            cu.display(),
            stderr.replace('\n', " | ")
        );
    }
    assert!(
        output.status.success(),
        "hipcc failed for {}:\n--- stderr ---\n{stderr}\n--- stdout ---\n{stdout}",
        cu.display()
    );
}
