//! TP-0a — peer-access registry smoke test.
//!
//! Exercises `HipCluster::new`'s on-construction probe of
//! `hipDeviceCanAccessPeer` + `hipDeviceEnablePeerAccess`. Runtime-skipped
//! on hosts with no HIP devices so `cargo test -p flambeau-backend-hip`
//! stays green on CI lint boxes that link `libamdhip64` without a GPU.
//!
//! The cert artefact (`certs/hip/gfx906/peer_access_matrix.json`) is
//! generated by the bench harness (TP-0c follow-up) — this test only
//! validates the API contract.

use flambeau_backend_hip::{device_count, HipCluster};

fn maybe_skip() -> Option<i32> {
    match device_count() {
        Ok(n) if n > 0 => Some(n),
        Ok(_) => {
            eprintln!("[skip] 0 HIP devices on this host");
            None
        }
        Err(e) => {
            eprintln!("[skip] HIP runtime not available: {e}");
            None
        }
    }
}

#[test]
fn single_rank_matrix_is_diagonal_true() {
    let Some(_) = maybe_skip() else { return };
    let cluster = HipCluster::new(&[0]).expect("HipCluster::new(&[0])");
    let m = cluster.peer_access_matrix();
    assert_eq!(m.len(), 1, "single-rank matrix must be 1x1");
    assert_eq!(m[0].len(), 1);
    assert!(m[0][0], "diagonal entry must be true");
    assert!(cluster.can_peer_access(0, 0));
    assert!(cluster.peer_access_full(), "single-rank cluster is trivially fully connected");
}

#[test]
fn multi_rank_matrix_diagonal_invariant() {
    let Some(n) = maybe_skip() else { return };
    if n < 2 {
        eprintln!("[skip] need >= 2 HIP devices for multi-rank peer-access test (have {n})");
        return;
    }
    // Take min(n, 4) so this works on 2/3/4-device rigs.
    let take = (n as usize).min(4);
    let device_ids: Vec<i32> = (0..take as i32).collect();
    let cluster = HipCluster::new(&device_ids).expect("HipCluster::new on multi-device rig");
    let m = cluster.peer_access_matrix();
    assert_eq!(m.len(), take);
    for i in 0..take {
        assert_eq!(m[i].len(), take, "row {i} must be {take}-wide");
        assert!(m[i][i], "diagonal entry [{i}][{i}] must be true");
    }
    println!("HipCluster::peer_access_matrix on {take}-device rig:");
    for (i, row) in m.iter().enumerate() {
        let cells: Vec<&'static str> = row.iter().map(|&b| if b { "1" } else { "0" }).collect();
        println!("  rank {i}: [{}]", cells.join(", "));
    }
    println!("peer_access_full = {}", cluster.peer_access_full());
}

#[test]
fn peer_access_query_handles_out_of_range() {
    let Some(_) = maybe_skip() else { return };
    let cluster = HipCluster::new(&[0]).expect("HipCluster::new(&[0])");
    // Out-of-range queries must not panic and must return false.
    assert!(!cluster.can_peer_access(0, 99));
    assert!(!cluster.can_peer_access(99, 0));
    assert!(!cluster.can_peer_access(99, 99));
}
