use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};
use std::process::Command;

use rayon::prelude::*;
use sha2::{Digest, Sha256};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/kernels");
    println!("cargo:rerun-if-changed=src/arch_primitives");
    println!("cargo:rerun-if-changed=../kernels-shared/include");
    println!("cargo:rerun-if-env-changed=CUDA_PATH");
    println!("cargo:rerun-if-env-changed=CUDA_ARCH");
    println!("cargo:rerun-if-env-changed=CUDA_SKIP_BUILD");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let src_dir = Path::new("src/kernels");
    let arch_inc = Path::new("src/arch_primitives");
    let shared_inc = Path::new("../kernels-shared/include");

    let skip_build = env::var_os("CUDA_SKIP_BUILD").is_some();
    let cu_files = enumerate_cu_files(src_dir);

    let mut entries: BTreeMap<String, PathBuf> = BTreeMap::new();
    if !skip_build && !cu_files.is_empty() {
        let cuda_path = env::var("CUDA_PATH").unwrap_or_else(|_| "/usr/local/cuda".into());
        let nvcc = find_nvcc(&cuda_path)
            .expect("nvcc not found — set CUDA_PATH or CUDA_SKIP_BUILD=1 to build without kernels");
        let arch = env::var("CUDA_ARCH").unwrap_or_else(|_| "sm_86".into());

        let cache_dir = out_dir.join("cache");
        let _ = fs::create_dir_all(&cache_dir);

        let results: Vec<(String, PathBuf)> = cu_files
            .par_iter()
            .map(|cu| {
                let stem = cu.file_stem().unwrap().to_string_lossy().into_owned();
                let cubin = out_dir.join(format!("{stem}.cubin"));
                let cache_hash_file = cache_dir.join(format!("{stem}.sha256"));

                if needs_rebuild(cu, &cubin, &cache_hash_file, &arch) {
                    compile_cu(
                        &nvcc,
                        cu,
                        &cubin,
                        &arch,
                        IncludeRoots { arch: arch_inc, shared: shared_inc, kernel: src_dir },
                    );
                    let hash = hash_cu_source(cu, &arch);
                    fs::write(&cache_hash_file, &hash).ok();
                }

                (stem, cubin)
            })
            .collect();
        for (stem, cubin) in results {
            entries.insert(stem, cubin);
        }
    }

    let mut cubin_rs = String::from("// Auto-generated by kernels-cuda/build.rs. Do not edit.\n\n");
    for (stem, path) in &entries {
        let const_name = stem.to_uppercase();
        writeln!(
            cubin_rs,
            "pub const {const_name}_CUBIN: &[u8] = include_bytes!(r\"{}\");",
            path.display()
        )
        .expect("write to String is infallible");
    }
    cubin_rs.push_str("\npub static CATALOGUE: &[(&str, &[u8])] = &[\n");
    for stem in entries.keys() {
        let const_name = stem.to_uppercase();
        writeln!(cubin_rs, "    (\"{stem}\", {const_name}_CUBIN),")
            .expect("write to String is infallible");
    }
    cubin_rs.push_str("];\n");
    fs::write(out_dir.join("cubin.rs"), cubin_rs).expect("write cubin.rs");
}

fn enumerate_cu_files(dir: &Path) -> Vec<PathBuf> {
    if !dir.exists() {
        return vec![];
    }
    fs::read_dir(dir)
        .expect("read kernels dir")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "cu"))
        .collect()
}

fn find_nvcc(cuda_path: &str) -> Option<PathBuf> {
    let candidates = [
        PathBuf::from(cuda_path).join("bin/nvcc"),
        PathBuf::from("/usr/local/cuda/bin/nvcc"),
        PathBuf::from("/usr/bin/nvcc"),
    ];
    candidates
        .into_iter()
        .find(|p| p.exists())
        .or_else(|| {
            env::var_os("PATH").and_then(|paths| {
                env::split_paths(&paths)
                    .map(|p| p.join("nvcc"))
                    .find(|p| p.exists())
            })
        })
}

fn hash_cu_source(cu: &Path, arch: &str) -> String {
    let mut hasher = Sha256::new();
    let mut f = fs::File::open(cu).expect("open cu file");
    let mut buf = Vec::new();
    f.read_to_end(&mut buf).expect("read cu file");
    hasher.update(&buf);
    hasher.update(arch.as_bytes());
    format!("{:x}", hasher.finalize())
}

fn needs_rebuild(cu: &Path, cubin: &Path, cache_hash: &Path, arch: &str) -> bool {
    if !cubin.exists() {
        return true;
    }
    if !cache_hash.exists() {
        return true;
    }
    let cached_hash = fs::read_to_string(cache_hash).unwrap_or_default().trim().to_string();
    hash_cu_source(cu, arch) != cached_hash
}

/// Include-path roots passed to `nvcc -I`.
struct IncludeRoots<'a> {
    arch: &'a Path,
    shared: &'a Path,
    kernel: &'a Path,
}

fn compile_cu(nvcc: &Path, cu: &Path, cubin: &Path, arch: &str, includes: IncludeRoots<'_>) {
    let IncludeRoots { arch: arch_inc, shared: shared_inc, kernel: kernel_inc } = includes;
    let output = Command::new(nvcc)
        .args([
            "--cubin",
            &format!("-arch={arch}"),
            "-std=c++17",
            "-O3",
            "-DWARP_SIZE=32",
            "-I",
            kernel_inc.to_str().unwrap(),
            "-I",
            arch_inc.to_str().unwrap(),
            "-I",
            shared_inc.to_str().unwrap(),
            "-o",
            cubin.to_str().unwrap(),
            cu.to_str().unwrap(),
        ])
        .output()
        .unwrap_or_else(|e| panic!("failed to run nvcc at {}: {e}", nvcc.display()));

    let stderr = String::from_utf8_lossy(&output.stderr);
    let stdout = String::from_utf8_lossy(&output.stdout);
    if !stdout.is_empty() {
        eprintln!("nvcc stdout for {}: {}", cu.display(), stdout.replace('\n', " | "));
    }
    if !stderr.is_empty() && !output.status.success() {
        eprintln!("nvcc stderr for {}: {}", cu.display(), stderr.replace('\n', " | "));
    }
    assert!(
        output.status.success(),
        "nvcc failed for {}:\n--- stderr ---\n{stderr}\n--- stdout ---\n{stdout}",
        cu.display()
    );
}
