#!/usr/bin/env python3
"""
MTP-2: Qwen3.6-27B MTP-head GGUF emitter.

Reads MTP shards 13 + 15 from the Qwen/Qwen3.6-27B BF16 release and
quantizes the 15 mtp.* tensors (linears → Q8_0, norms stay F32).

Two output modes:

THIN (default) — emit a small standalone `*-mtp.gguf` (~451 MB)
that the flambeau loader pairs with ANY existing base Qwen3.6-27B
GGUF (Q4_0 / Q4_1 / Q8_0 / UD-Q4_K_XL / UD-Q6_K_XL / …) at runtime.
The pair-up requires a couple of metadata keys (`mtp.target_arch`,
`mtp.target_hidden_size`, `mtp.target_vocab_size`,
`mtp.source_repo`) which the loader verifies against the base's own
metadata. Disk cost across all variants you own is +451 MB ONCE.

INTEGRATE (`--integrate-into <base>`) — emit a `<base>+mtp.gguf` that
copies the base verbatim and appends the MTP tensors. Useful for
distribution as a single file but costs ~base_size disk per variant
(+1 base size if you already have the base — typically wasteful).

Usage (thin, recommended):
    python tools/convert_qwen36_mtp.py \\
        --shards-dir tools/mtp_cache \\
        --out /artefact/models/Qwen3.6-27B-mtp.gguf

Usage (integrated):
    python tools/convert_qwen36_mtp.py \\
        --shards-dir tools/mtp_cache \\
        --integrate-into /artefact/models/Qwen3.6-27B-Q4_0.gguf \\
        --out /artefact/models/Qwen3.6-27B-Q4_0+mtp.gguf
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import numpy as np
import torch
from safetensors import safe_open

import gguf.quants
from gguf import GGMLQuantizationType, GGUFReader, GGUFValueType, GGUFWriter

# Auto-generated by GGUFWriter; we rebuild them rather than copy.
SKIP_FIELDS: set[str] = {"GGUF.version", "GGUF.tensor_count", "GGUF.kv_count"}

# Per-tensor target quant for the MTP head.
def _linear_dtype() -> GGMLQuantizationType:
    """Linear-weight target. Default F16 (lower precision-loss vs Q8_0; 3.5×
    larger but the MTP block is only 393M params so the absolute disk cost is
    ~+800 MB). Set MTP_LINEAR_DTYPE=q8_0 or =f16 to override."""
    import os
    v = os.environ.get("MTP_LINEAR_DTYPE", "f16").lower()
    if v == "q8_0":
        return GGMLQuantizationType.Q8_0
    if v == "f16":
        return GGMLQuantizationType.F16
    raise SystemExit(f"unsupported MTP_LINEAR_DTYPE={v!r}; use q8_0 or f16")

_LIN = _linear_dtype()

MTP_TENSOR_DTYPES: dict[str, GGMLQuantizationType] = {
    # Norms → F32 (small; norms are precision-sensitive).
    "mtp.norm.weight":                              GGMLQuantizationType.F32,
    "mtp.pre_fc_norm_embedding.weight":             GGMLQuantizationType.F32,
    "mtp.pre_fc_norm_hidden.weight":                GGMLQuantizationType.F32,
    "mtp.layers.0.input_layernorm.weight":          GGMLQuantizationType.F32,
    "mtp.layers.0.post_attention_layernorm.weight": GGMLQuantizationType.F32,
    "mtp.layers.0.self_attn.q_norm.weight":         GGMLQuantizationType.F32,
    "mtp.layers.0.self_attn.k_norm.weight":         GGMLQuantizationType.F32,
    # Linears → configurable (default F16; was Q8_0 in MTP-3 cert).
    "mtp.fc.weight":                                _LIN,
    "mtp.layers.0.self_attn.q_proj.weight":         _LIN,
    "mtp.layers.0.self_attn.k_proj.weight":         _LIN,
    "mtp.layers.0.self_attn.v_proj.weight":         _LIN,
    "mtp.layers.0.self_attn.o_proj.weight":         _LIN,
    "mtp.layers.0.mlp.gate_proj.weight":            _LIN,
    "mtp.layers.0.mlp.up_proj.weight":              _LIN,
    "mtp.layers.0.mlp.down_proj.weight":            _LIN,
}


def load_mtp_tensors(shards_dir: Path) -> dict[str, np.ndarray]:
    """
    Read all `mtp.*` tensors from shards 13+15 as F32 numpy arrays.

    **GemmaRMSNorm `+1` convention.** Qwen3-Next (and Qwen3.5/3.6) uses
    GemmaRMSNorm: `output = (1 + weight) * x / rms(x)`. llama.cpp's GGUF
    convention bakes the `+1` into the stored weight so standard
    RMSNorm `weight * x / rms(x)` produces the same result. The base
    model's GGUF has this transformation applied (verified empirically:
    base norm weights cluster around mean ≈ 1.0). The MTP weights in
    Qwen/Qwen3.6-27B's safetensors are RAW (mean ≈ 0); we apply the
    same `+1` here so flambeau's standard RMSNorm consumes them
    correctly without any model-side change. Without this, MTP forward
    multiplies activations by ≈ 0 and produces nonsense — confirmed
    diagnosis 2026-04-29 against base/MTP norm-weight statistics.
    """
    tensors: dict[str, np.ndarray] = {}
    for shard_name in ("shard-13.safetensors", "shard-15.safetensors"):
        path = shards_dir / shard_name
        if not path.exists():
            raise SystemExit(f"missing shard: {path}")
        with safe_open(str(path), framework="pt") as f:
            for key in f.keys():
                if not key.startswith("mtp."):
                    continue
                if key not in MTP_TENSOR_DTYPES:
                    raise SystemExit(f"unexpected MTP tensor in safetensors: {key}")
                t = f.get_tensor(key).to(torch.float32).numpy()
                # Norm weights → bake +1 (GemmaRMSNorm convention).
                if MTP_TENSOR_DTYPES[key] is GGMLQuantizationType.F32 and key.endswith(".weight"):
                    # All MTP norms map to F32 in MTP_TENSOR_DTYPES; this
                    # key-suffix check is just a belt-and-braces guard.
                    is_norm = (
                        "norm" in key
                        or key.endswith("layernorm.weight")
                        or key == "mtp.norm.weight"
                    )
                    if is_norm:
                        t = t + 1.0
                tensors[key] = t
    missing = set(MTP_TENSOR_DTYPES) - set(tensors)
    if missing:
        raise SystemExit(f"missing MTP tensors in shards: {sorted(missing)}")
    return tensors


def quantize_mtp(name: str, fp32: np.ndarray) -> tuple[np.ndarray, GGMLQuantizationType]:
    qtype = MTP_TENSOR_DTYPES[name]
    if qtype is GGMLQuantizationType.F32:
        return np.ascontiguousarray(fp32, dtype=np.float32), qtype
    if qtype is GGMLQuantizationType.F16:
        return np.ascontiguousarray(fp32.astype(np.float16)), qtype
    if qtype is GGMLQuantizationType.Q8_0:
        if fp32.shape[-1] % 32 != 0:
            raise SystemExit(f"{name}: last dim {fp32.shape[-1]} not multiple of 32 (Q8_0 block)")
        return gguf.quants.quantize(fp32, GGMLQuantizationType.Q8_0), qtype
    raise SystemExit(f"unsupported quant for {name}: {qtype}")


def copy_kv_fields(reader: GGUFReader, writer: GGUFWriter) -> int:
    """
    Copy every metadata field from `reader` to `writer` using the generic
    `add_key_value` API. Returns the number copied.
    """
    n = 0
    for fname, field in reader.fields.items():
        if fname in SKIP_FIELDS:
            continue
        # `field.types` is a list. For arrays it's [ARRAY, sub_type]; for
        # scalars it's a single-element list with the value type.
        outer = field.types[0]
        if outer is GGUFValueType.ARRAY:
            sub = field.types[-1]
            val = field.contents()
            writer.add_key_value(fname, val, GGUFValueType.ARRAY, sub_type=sub)
        else:
            val = field.contents()
            writer.add_key_value(fname, val, outer)
        n += 1
    return n


def quantize_all_mtp(
    shards_dir: Path,
) -> dict[str, tuple[np.ndarray, GGMLQuantizationType, tuple[int, ...]]]:
    """Read shards, quantize the 15 MTP tensors, return ready-to-write entries."""
    print(f"loading MTP from: {shards_dir}")
    mtp_fp32 = load_mtp_tensors(shards_dir)
    print(f"  MTP tensors loaded: {len(mtp_fp32)}")

    print("quantizing MTP tensors...")
    out: dict[str, tuple[np.ndarray, GGMLQuantizationType, tuple[int, ...]]] = {}
    total = 0
    for name, fp32 in mtp_fp32.items():
        q, qtype = quantize_mtp(name, fp32)
        logical_shape = tuple(int(d) for d in fp32.shape)
        out[name] = (q, qtype, logical_shape)
        total += q.nbytes
        print(f"  {name}: {logical_shape} f32 → {qtype.name} ({q.nbytes/1e6:.2f} MB)")
    print(f"  MTP total: {total/1e6:.2f} MB")
    return out


def write_thin_mtp_gguf(
    out_path: Path,
    mtp_quantized: dict[str, tuple[np.ndarray, GGMLQuantizationType, tuple[int, ...]]],
    target_arch: str,
    target_hidden_size: int,
    target_vocab_size: int,
    source_repo: str,
) -> None:
    """Emit a small standalone *-mtp.gguf (no base tensors)."""
    writer = GGUFWriter(str(out_path), arch=f"{target_arch}-mtp")
    # Pairing metadata — flambeau's loader checks these against the base.
    writer.add_string("mtp.source_repo", source_repo)
    writer.add_string("mtp.target_arch", target_arch)
    writer.add_uint32("mtp.target_hidden_size", target_hidden_size)
    writer.add_uint32("mtp.target_vocab_size", target_vocab_size)
    writer.add_uint32("mtp.num_layers", 1)
    writer.add_bool("mtp.use_dedicated_embeddings", False)

    for name, (q, qtype, _logical_shape) in mtp_quantized.items():
        writer.add_tensor(
            name,
            q,
            raw_shape=tuple(int(d) for d in q.shape),
            raw_dtype=qtype,
        )
    print(f"  writing thin MTP GGUF...")
    writer.write_header_to_file()
    writer.write_kv_data_to_file()
    writer.write_tensors_to_file(progress=True)
    writer.close()


def write_integrated_mtp_gguf(
    out_path: Path,
    base_reader: GGUFReader,
    mtp_quantized: dict[str, tuple[np.ndarray, GGMLQuantizationType, tuple[int, ...]]],
    arch: str,
    source_repo: str,
) -> None:
    """Emit <base>+mtp.gguf — verbatim copy of base + MTP tensors appended."""
    writer = GGUFWriter(str(out_path), arch=arch)

    n_kv = copy_kv_fields(base_reader, writer)
    writer.add_string("mtp.source_repo", source_repo)
    writer.add_uint32("mtp.num_layers", 1)
    writer.add_bool("mtp.use_dedicated_embeddings", False)
    print(f"  KV fields copied: {n_kv} (+ 3 mtp.* fields)")

    print(f"  adding tensor descriptors...")
    for t in base_reader.tensors:
        writer.add_tensor(
            t.name,
            t.data,
            raw_shape=tuple(int(d) for d in t.data.shape),
            raw_dtype=t.tensor_type,
        )
    for name, (q, qtype, _logical_shape) in mtp_quantized.items():
        writer.add_tensor(
            name,
            q,
            raw_shape=tuple(int(d) for d in q.shape),
            raw_dtype=qtype,
        )
    print(f"  tensors total: {len(base_reader.tensors) + len(mtp_quantized)}")
    writer.write_header_to_file()
    writer.write_kv_data_to_file()
    print("  writing tensors (this streams the entire base — may take a minute)...")
    writer.write_tensors_to_file(progress=True)
    writer.close()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--shards-dir", required=True, type=Path,
                    help="Directory containing shard-13.safetensors and shard-15.safetensors.")
    ap.add_argument("--out", required=True, type=Path,
                    help="Output GGUF path. Will be overwritten if it exists.")
    ap.add_argument("--integrate-into", type=Path, default=None,
                    help="Optional: a base Qwen3.6-27B GGUF to copy verbatim and append MTP into. "
                         "If omitted, emits a thin standalone MTP-only GGUF (recommended).")
    ap.add_argument("--source-repo", default="Qwen/Qwen3.6-27B",
                    help="Stamped into mtp.source_repo metadata.")
    # For thin mode, these come from the user's base file or are passed manually.
    ap.add_argument("--target-arch", default="qwen35",
                    help="(thin mode) target architecture name; pair check at load time.")
    ap.add_argument("--target-hidden-size", type=int, default=5120,
                    help="(thin mode) target hidden size; pair check.")
    ap.add_argument("--target-vocab-size", type=int, default=248320,
                    help="(thin mode) target vocab size; pair check.")
    args = ap.parse_args()

    if not args.shards_dir.exists():
        raise SystemExit(f"shards dir not found: {args.shards_dir}")
    args.out.parent.mkdir(parents=True, exist_ok=True)

    mtp_quantized = quantize_all_mtp(args.shards_dir)
    del_mtp_fp32 = None  # keep `mtp_quantized` only

    if args.integrate_into is None:
        # THIN mode (default).
        print(f"writing thin MTP-only GGUF: {args.out}")
        write_thin_mtp_gguf(
            args.out,
            mtp_quantized,
            target_arch=args.target_arch,
            target_hidden_size=args.target_hidden_size,
            target_vocab_size=args.target_vocab_size,
            source_repo=args.source_repo,
        )
    else:
        # INTEGRATE mode.
        if not args.integrate_into.exists():
            raise SystemExit(f"--integrate-into not found: {args.integrate_into}")
        print(f"reading base: {args.integrate_into}")
        reader = GGUFReader(str(args.integrate_into))
        arch = str(reader.fields["general.architecture"].contents())
        print(f"  arch: {arch}, tensors: {len(reader.tensors)}, fields: {len(reader.fields)}")
        if arch != "qwen35":
            raise SystemExit(
                f"this converter is for arch=qwen35 (Qwen3.6-27B); got arch={arch}."
            )
        print(f"writing integrated GGUF: {args.out}")
        write_integrated_mtp_gguf(
            args.out, reader, mtp_quantized,
            arch=arch, source_repo=args.source_repo,
        )

    out_size = args.out.stat().st_size
    print(f"done: {args.out} ({out_size/1e6:.2f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
